### ISSUE TITLE
Fix Token Transfer unit conversion for decimal value

### ISSUE THREAD

**Issue by VagPanour** [geometry-labs/icon-explorer#56]
Some tokens (i.e. iUSDT or iUSDC) use a 6 decimal conversion value instead of 18 (standard for most tokens). A fix is needed in order the key 'value_decimal' to return the correct decimal value in both cases. Example below

![6decimal](https://user-images.githubusercontent.com/93825444/140610190-a65a41a2-a67b-416a-8063-54eeafbf3894.JPG)
![18decimal](https://user-images.githubusercontent.com/93825444/140610191-0f8f112c-d7e0-406b-a18a-179f4dc6a45b.JPG)
.

**Comment by pranav925** [comment]
use redis to cache

**Comment by robcxyz** [comment]
Going to require a backfill
